let languageContent = {
    en: {
        "nav-home": "Home",
        "nav-about": "About",
        "nav-projects": "Projects",
        "nav-resume": "Resume",
        "nav-contact": "Contact",
        welcome: "Welcome",
        iam: "I<span>'</span>m",
        "title-1": "Data Analyst",
        "title-2": "Graphic Designer",
        "title-3": "UI/UX Designer",
        download: "Download CV",
        "about-title": "About",
        "about-text-1":
            "Hello, I'm Rajif, a Graphic Designer and Data Analyst. I have expertise in Statistic (R, SPSS, Excel, Minitab), Front-End (HTML, CSS, JS, Bootstrap), Back-End (Python), and Graphic Design (Photoshop, Illustrator). In addition, I also have additional skills in UI/UX Design (Figma) and IoT.",
        "about-text-2":
            "I have worked in several communities as a Graphic Designer. I am very enthusiastic about developing my skills and seeking opportunities to work in a company that allows me to learn and contribute.",
        "about-text-3":
            "Thank you for visiting my website. I hope to collaborate with you on interesting and beneficial projects. Please don't hesitate to contact me if you have any questions or would like to discuss further how I can help you.",
        my: "My",
        "skills-2": "Skills",
        learning: "Currently Learning",
        "inter-1": "Intermediate",
        "inter-2": "Intermediate",
        "inter-3": "Intermediate",
        advanced: "Advanced",
        "projects-title": "Projects",
        "project-1": "Nasional Data Science Tournament",
        "project-2": "Training by UKMKI Unair",
        "project-3": "Training by FTMM Unair",
        "resume-title": "Resume",
        "resume-capt":
            "In this section, you will find my educational background and work experience. I believe that my academic achievements and professional experiences have equipped me with the necessary skills and knowledge to excel in the field. I am a firm believer in continuous learning, and I strive to apply my skills to create impactful solutions. Please take a look at my educational qualifications and work history to learn more about my journey so far.",
        "edu-title": "Education",
        "edu-1": "MAS Hasyim Asy'ari",
        "edu-1-award-1": "2nd Place in Biology Olympiad",
        "edu-1-award-2": "1st Place in Table Tennis Competition",
        "edu-2": "Airlangga University",
        "edu-2-award-1": "Participants of the National Data Science Tournament",
        "edu-2-award-2": "Participants of the National Level Data Satria Competition",
        exp: "Experience",
        "it-staff": "Staff",
        "present-1": "Present",
        "present-2": "Present",
        "present-3": "Present",
        jarkot: "Commite Pelayanan Sosial",
        "graphic-1": "Head Divison",
        "graphic-2": "Staff",
        "contact-title": "Contact",
        "contact-text":
            'Feel free to reach out to me via email or social media. I am always open to new <span class="highlight">opportunies</span> and <span class="highlight" >collaborations</span>',
        "add-1": "Jl. Masjid Induk No.3 Bulungan Pakis Aji, Jepara",
        "add-2": "Jl. Suterejo Selatan II No.11, Mulyorejo, Surabaya",
        send: "Send",
        created: "Created by Eternal Code",
    },
    id: {
        "nav-home": "Beranda",
        "nav-about": "Tentang",
        "nav-projects": "Proyek",
        "nav-resume": "Ringkasan",
        "nav-contact": "Kontak",
        "welcome": "Selamat Datang",
        "iam": "Saya",
        "title-1": "Data Analisis",
        "title-2": "Desain Grafis",
        "title-3": "UI/UX Designer",
        "download": "Unduh CV",
        "about-title": "Tentang",
        "about-text-1":
            "Halo, saya Rajif, seorang Data Analisis dan Desainer Grafis. Saya memiliki keahlian di Statistic (R, SPSS, Excel, Minitab) Front-End (HTML, CSS, JS, Bootstrap), Back-End (Python), dan Desain Grafis (Photoshop, Illustrator). Selain itu, saya juga memiliki keterampilan tambahan di Desain UI/UX (Figma) dan IoT.",
        "about-text-2":
            "Saya pernah bekerja di beberapa komunitas sebagai Desainer Grafis. Saya sangat antusias dalam mengembangkan kemampuan saya dan mencari kesempatan untuk bekerja di perusahaan yang memungkinkan saya untuk belajar dan berkontribusi.",
        "about-text-3":
            "Terima kasih telah mengunjungi website saya. Saya berharap dapat berkolaborasi dengan Anda dalam proyek yang menarik dan bermanfaat. Jangan ragu untuk menghubungi saya jika Anda memiliki pertanyaan atau ingin membahas lebih lanjut bagaimana saya dapat membantu Anda.",
        "my": "Keahlian",
        "skills-2": "Saya",
        "learning": "Sedang dipelajari",
        "inter-1": "menengah",
        "inter-2": "Menengah",
        "inter-3": "Menengah",
        "advanced": "Tingkat Lanjut",
        "projects-title": "Proyek",
        "project-1": "Tournament Sains Data Tingkat Nasional",
        "project-2": "Pelatihan by UKMKI Unair",
        "project-3": "Pelatihan by FTMM Unair",
        "resume-title": "Ringkasan",
        "resume-capt":
            "Berikut adalah latar belakang pendidikan dan pengalaman kerja saya. Saya percaya bahwa prestasi akademik dan pengalaman profesional saya telah membekali saya dengan keterampilan dan pengetahuan yang diperlukan untuk menjadi unggul di bidang ini. Saya sangat mempercayai pembelajaran berkelanjutan, dan saya berusaha untuk menerapkan keterampilan saya untuk menciptakan solusi yang berdampak positif. Silakan lihat kualifikasi pendidikan dan riwayat kerja saya untuk mempelajari lebih lanjut tentang perjalanan saya selama ini.",
        "edu-title": "Pendidikan",
        "edu-1": "MAS Hasyim Asy'ari",
        "edu-1-award-1": "Juara 2 Lomba Olempiade Biologi",
        "edu-1-award-2": "Juara 1 Lomba Tenis Meja",
        "edu-2": "Universitas Airlangga",
        "edu-2-award-1": "Peserta Lomba Tournament Sains Data Tingkat Nasional",
        "edu-2-award-2": "Peserta Lomba Satria Data Tingkat Nasional",
        "exp": "Pengalaman",
        "it-staff": "Staff",
        "present-1": "Sekarang",
        "present-2": "Sekarang",
        "present-3": "Sekarang",
        "jarkot": "Commite Pelayanan Sosial",
        "graphic-1": "Head Division",
        "graphic-2": "Staff",
        "contact-title": "Kontak",
        "contact-text":
            'Jangan ragu untuk menghubungi saya melalui email atau media sosial. Saya selalu terbuka untuk <span class="highlight">kesempatan</span> dan <span class="highlight">kolaborasi</span> baru.',
        "add-1": "Jl. Masjid Induk No.3 Bulungan Pakis Aji, Jepara",
        "add-2": "Jl. Suterejo Selatan II No.11, Mulyorejo, Surabaya",
        "send": "Kirim",
        "created": "Dibuat oleh Eternal Code",
    },
};
function switchLang(lang) {
    for (let key in languageContent[lang]) {
        document.getElementById(key).innerHTML = languageContent[lang][key];
    }
}